version: '3.8'
services:
  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: service/Dockerfile
    env_file:
      - service/.env
    ports:
      - "5000:5000"
