name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests
        run: |
          poetry run pytest --cov=./ --cov-report=xml

      - name: Check code coverage
        run: |
          poetry run coverage report --fail-under=80

          - name: Start the web app
          run: |
            poetry run python app.py &
            
      - name: Wait for the web app to start
        run: sleep 5
